Repository jenkins-x-charts/knative-build, pull requests merged in 2019-01, with the labels that each got.

#15 Fix build-controller image
  knative-build/values.yaml
Labels: approved, ok-to-test, size/XS

#13 Add missing privileges to knative-build-bot to perform helm releases
  knative-build/templates/build-bot-role.yaml
  knative-build/templates/build-bot-tiller-role.yaml
  knative-build/templates/build-bot-tiller-rolebinding.yaml
  knative-build/values.yaml
Labels: approved, ok-to-test, size/M

#17 add Ingress to the role
  knative-build/templates/build-bot-role.yaml
Labels: approved, size/S

#18 feat: added required roles to be able to start/manage a kaniko build pod
  knative-build/templates/build-bot-role.yaml
Labels: approved, size/S

#19 allow users to be updated
  knative-build/templates/build-bot-role.yaml
Labels: approved, size/XS

#21 Enable read access to extensions
  knative-build/templates/build-bot-role.yaml
Labels: approved, ok-to-test, size/XS

#20 fix: allow knative-build-bot to ing/services
  knative-build/templates/build-bot-clusterrole.yaml
Labels: approved, ok-to-test, size/S

#11 fix: using Release.Namespace in the ClusterRoleBinding name
  knative-build/Makefile
  knative-build/templates/build-bot-clusterrolebinding.yaml
  knative-build/templates/build-clusterrolebinding.yaml
  knative-build/templates/helm-clusterrolebinding.yaml
Labels: approved, size/S
